# Generated by Django 4.2.13 on 2026-08-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('art_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('art_nomb', models.CharField(blank=True, help_text='Nombre articulo', max_length=100, null=True)),
                ('art_medi', models.CharField(blank=True, help_text='Medida', max_length=100, null=True)),
                ('art_umed', models.CharField(blank=True, help_text='Unidad de medida', max_length=100, null=True)),
                ('art_uequ', models.CharField(blank=True, help_text='Unidades x bulto', max_length=100, null=True)),
                ('art_ucos', models.DecimalField(blank=True, decimal_places=2, help_text='Costo', max_digits=30, null=True)),
                ('art_tprec', models.CharField(blank=True, help_text='Tipo precio', max_length=20, null=True)),
                ('art_prec', models.DecimalField(decimal_places=2, help_text='Precio articulo', max_digits=30, null=True)),
                ('art_pnet', models.DecimalField(blank=True, decimal_places=2, help_text='Precio neto', max_digits=30, null=True)),
                ('art_pfin', models.DecimalField(blank=True, decimal_places=2, help_text='Precio final', max_digits=30, null=True)),
                ('art_tiva', models.DecimalField(decimal_places=2, default=0, help_text='IVA articulo(%)', max_digits=30, null=True)),
                ('art_iint', models.DecimalField(decimal_places=2, default=0, help_text='Total impuesto interno', max_digits=30, null=True)),
                ('art_habi', models.BooleanField(default=False, help_text='Articulo habilitado/no', null=True)),
                ('art_pesa', models.BooleanField(default=False, help_text='Pesable/no', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanalVenta',
            fields=[
                ('can_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('can_nomb', models.CharField(help_text='Nombre canal de venta', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cli_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('cli_nomb', models.CharField(help_text='Nombre del cliente', max_length=100, null=True)),
                ('cli_dire', models.CharField(blank=True, help_text='Dirección', max_length=100, null=True)),
                ('cli_celu', models.CharField(blank=True, help_text='Celular', max_length=20, null=True)),
                ('cli_emai', models.CharField(blank=True, help_text='Email', max_length=100, null=True)),
                ('cli_ndoc', models.CharField(blank=True, help_text='Numero documento', max_length=20, null=True)),
                ('cli_cuit', models.CharField(blank=True, help_text='CUIT', max_length=20, null=True)),
                ('cli_alta', models.DateField(blank=True, help_text='Fecha alta cliente', null=True)),
                ('cli_baja', models.DateField(blank=True, help_text='Fecha baja cliente', null=True)),
                ('can_codi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_canal', to='gestion.canalventa')),
            ],
        ),
        migrations.CreateModel(
            name='ComodinArticulo',
            fields=[
                ('art_ccom', models.IntegerField(primary_key=True, serialize=False)),
                ('art_ncom', models.CharField(blank=True, help_text='Nombre comodin', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComodinCliente',
            fields=[
                ('cli_ccom', models.IntegerField(primary_key=True, serialize=False)),
                ('cli_ncom', models.CharField(blank=True, help_text='Nombre comodin', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComodinVenta',
            fields=[
                ('vta_ccom', models.IntegerField(primary_key=True, serialize=False)),
                ('vta_ncom', models.CharField(blank=True, help_text='Nombre comodin', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionIva',
            fields=[
                ('civ_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('civ_nomb', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('gen_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('gen_nomb', models.CharField(blank=True, help_text='Nombre de la empresa', max_length=150, null=True)),
                ('gen_logo', models.ImageField(blank=True, help_text='Logo', null=True, upload_to='logos/')),
                ('gen_cuit', models.CharField(default='00-00000000-0', help_text='CUIT de la empresa', max_length=20, null=True)),
                ('gen_dire', models.CharField(blank=True, help_text='Direccion', max_length=150, null=True)),
                ('gen_tele', models.CharField(blank=True, help_text='Telefono', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('grc_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('grc_nomb', models.CharField(blank=True, help_text='Nombre grupo cliente', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('loc_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('loc_nomb', models.CharField(blank=True, help_text='Nombre localidad', max_length=100)),
                ('loc_cpos', models.IntegerField(blank=True, help_text='Codigo postal', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('mar_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('mar_nomb', models.CharField(blank=True, help_text='Nombre marca', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('pci_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('pci_nomb', models.CharField(blank=True, help_text='Nombre provincia', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('rub_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('rub_nomb', models.CharField(blank=True, help_text='Nombre rubro', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMarca',
            fields=[
                ('smar_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('smar_nomb', models.CharField(blank=True, help_text='Sub marca', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('suc_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('suc_nomb', models.CharField(blank=True, help_text='Nombre sucursal', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zon_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('zon_nomb', models.CharField(blank=True, help_text='Nombre zona', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('vta_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('vta_fech', models.DateField(blank=True, help_text='Fecha venta', null=True)),
                ('vta_cvta', models.CharField(blank=True, help_text='Condicion de', max_length=3, null=True)),
                ('vta_itoR', models.DecimalField(decimal_places=2, help_text='Total real', max_digits=30, null=True)),
                ('vta_igra', models.DecimalField(decimal_places=2, help_text='Importe gravado', max_digits=30, null=True)),
                ('vta_iexe', models.DecimalField(decimal_places=2, help_text='Importe exento', max_digits=30, null=True)),
                ('vta_iiva', models.DecimalField(decimal_places=2, help_text='IVA del artículo (%)', max_digits=30, null=True)),
                ('vta_iiin', models.DecimalField(decimal_places=2, help_text='Importe de impuesto interno', max_digits=30, null=True)),
                ('vta_ibts', models.DecimalField(decimal_places=2, help_text='Total ingreso brutos', max_digits=30, null=True)),
                ('cli_codi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='gestion.clientes')),
                ('gen_codi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='General', to='gestion.general')),
                ('suc_codi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='gestion.sucursal')),
                ('vta_ccom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='gestion.comodinventa')),
            ],
        ),
        migrations.CreateModel(
            name='SubRubro',
            fields=[
                ('sru_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('sru_nomb', models.CharField(blank=True, help_text='Subrubro nombre', max_length=100, null=True)),
                ('rub_codi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Rubro', to='gestion.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('pro_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('Pro_nomb', models.CharField(blank=True, help_text='Nombre proveedor', max_length=100, null=True)),
                ('pro_Cuit', models.CharField(blank=True, help_text='CUIT', max_length=20, null=True)),
                ('pro_dire', models.CharField(blank=True, help_text='Dirección', max_length=100, null=True)),
                ('pro_celu', models.CharField(blank=True, help_text='Celular', max_length=20, null=True)),
                ('pro_ibru', models.CharField(blank=True, help_text='Ingresos brutos', max_length=30, null=True)),
                ('civ_codi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='gestion.condicioniva')),
                ('loc_codi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='gestion.localidad')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='pci_codi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Provincia', to='gestion.provincia'),
        ),
        migrations.CreateModel(
            name='LegajoPersonal',
            fields=[
                ('per_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('per_nomb', models.CharField(help_text='Nombre legajo personal', max_length=100, null=True)),
                ('per_Ndoc', models.CharField(blank=True, help_text='Nro documento', max_length=20, null=True)),
                ('Per_CUIL', models.CharField(blank=True, help_text='CUIL', max_length=20, null=True)),
                ('Per_Celu', models.CharField(blank=True, help_text='Celular', max_length=20, null=True)),
                ('Per_mail', models.CharField(blank=True, help_text='Email', max_length=100, null=True)),
                ('per_alta', models.DateField(blank=True, help_text='Fecha alta legajo', null=True)),
                ('per_baja', models.DateField(blank=True, help_text='Fecha baja legajo', null=True)),
                ('Per_domi', models.CharField(blank=True, help_text='Dirección', max_length=100, null=True)),
                ('loc_codi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legajo_direccion', to='gestion.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('dvt_codi', models.BigAutoField(primary_key=True, serialize=False)),
                ('dvt_iOri', models.DecimalField(decimal_places=2, help_text='Importe original sin bonificacion', max_digits=30, null=True)),
                ('dvt_iuni', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=30, null=True)),
                ('dvt_itot', models.DecimalField(decimal_places=2, help_text='Total', max_digits=30, null=True)),
                ('dvt_cost', models.DecimalField(decimal_places=2, help_text='Costo', max_digits=30, null=True)),
                ('dvt_iiva', models.DecimalField(decimal_places=2, help_text='detalle IVA del artículo (%)', max_digits=30, null=True)),
                ('dvt_igra', models.DecimalField(decimal_places=2, help_text='Importe gravado', max_digits=30, null=True)),
                ('dvt_iexe', models.DecimalField(decimal_places=2, help_text='Importe exento', max_digits=30, null=True)),
                ('dvt_iint', models.DecimalField(decimal_places=2, help_text='Impuesto interno unitario', max_digits=30, null=True)),
                ('dvt_caPi', models.DecimalField(decimal_places=2, help_text='Cantidad de piezas en pesables', max_digits=30, null=True)),
                ('dvt_cant', models.DecimalField(decimal_places=2, help_text='Cantidad', max_digits=30, null=True)),
                ('art_codi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='gestion.articulos')),
                ('vta_codi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='gestion.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Cobranzas',
            fields=[
                ('cob_codi', models.IntegerField(primary_key=True, serialize=False)),
                ('cob_fech', models.DateField(blank=True, help_text='Fecha cobro', null=True)),
                ('cob_itot', models.DecimalField(blank=True, decimal_places=2, help_text='cobro total', max_digits=30, null=True)),
                ('cli_codi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobranzas', to='gestion.clientes')),
                ('suc_codi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobranzas', to='gestion.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='civ_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='gestion.condicioniva'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cli_ccom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComodinCliente', to='gestion.comodincliente'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='grc_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='gestion.grupocliente'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='loc_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='gestion.localidad'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='per_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='gestion.legajopersonal'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='zon_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Zona', to='gestion.zona'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='art_ccom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComodinArticulo', to='gestion.comodinarticulo'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='mar_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Marca', to='gestion.marca'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='pro_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Proveedor', to='gestion.proveedor'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='smar_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Submarca', to='gestion.submarca'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='sru_codi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Subrubro', to='gestion.subrubro'),
        ),
        migrations.AddConstraint(
            model_name='ventas',
            constraint=models.UniqueConstraint(fields=('cli_codi', 'vta_fech', 'vta_cvta', 'suc_codi', 'vta_ccom', 'gen_codi'), name='uk_venta'),
        ),
        migrations.AddConstraint(
            model_name='detalleventa',
            constraint=models.UniqueConstraint(fields=('vta_codi', 'art_codi'), name='uk_detalle_venta'),
        ),
    ]
