# Generated by Django 4.2.13 on 2026-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='dvt_iiva',
            field=models.DecimalField(decimal_places=2, help_text='detalle IVA del artículo (%)', max_digits=30, null=True),
        ),
    ]
