# Generated by Django 4.2.13 on 2026-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='dvt_cant',
            field=models.IntegerField(blank=True, help_text='detalle cantidad', null=True),
        ),
    ]
