# Generated by Django 4.2.13 on 2026-08-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='vta_canc',
            field=models.IntegerField(blank=True, help_text='Cantidad de comprobantes', null=True),
        ),
    ]
