# Generated by Django 4.2.13 on 2026-08-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_detalleventa_dvt_iiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='dvt_cant',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad', max_digits=30, null=True),
        ),
    ]
