# Generated by Django 4.2.13 on 2026-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_detalleventa_dvt_cant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='vta_itoR',
            field=models.DecimalField(decimal_places=2, help_text='Total real', max_digits=30, null=True),
        ),
    ]
